### PR TITLE
Python Package

### PR DESCRIPTION
**Pull request by undu**
This makes sequestrum installable using pip, and friendlier to distro packagers.

### CODE REVIEW

**Comment by countingsort** [comment]
Also:

- Added .gitignore
- Restructed a little (source -> sequestrum)

**Comment by countingsort** [comment]
@undu I figured later. I normally don't do python, just wanted to be helpful.

**Comment by countingsort** [comment]
Would fix #2

**Comment by iiPlasma** [comment]
Hey @undu! Thanks so much for contributing, and this is actually awesome! Could you fix the conflicts and then I'l merge it into master. Hopefully I fix the structure soon and you can just merge to the develop branch next time. Have a good day!

**Comment by iiPlasma** [comment]
@undu Hey.... so how are users supposed to use pip to install this? I've personally never used pip before in a project xD

**Comment by iiPlasma** [comment]
Alright thanks so I should only push to GitHub and upload to pip the releases that have a tag? Than

**Comment by undu** [comment]
The release process would be:
- Prepare readmes, changelogs, etc
- Tag the commit in git (also upload it to github)
- Make the package from the tagged commit & upload

**Comment by iiPlasma** [comment]
Thanks so much!

**Comment by iiPlasma** [comment]
Hey @undu I've been trying to upload a new version but it's giving me 
```
HTTPError: 400 Client Error: File already exists. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/
```
I've been doing 
1. `git add .`
2. 'git commit -m "Some Message"`
3. `git tag <tagname>`
4. `git push origin <tagname>`

Then i've been doing the steps you said up there, but it isn't uploading. If you could help that'd be awesome. Thanks c:

**Comment by iiPlasma** [comment]
`twine upload -r pypi dist/sequestrum-<version_number>*`

Find version number in dict
This is what I had to do to fix it and have it uplaod the correct file.

**Pull request merged**
