### PR TITLE
Logging feature! Also major rewrite and cleanup

### PR DESCRIPTION
**Pull request by nawuko**
* Refactored almost every function to accommodate for logging.
* Also cleaned up some unneeded iterations and code duplication.
* Added a logger with ANSI color support and different log levels
* Added --verbose flag for verbose logging
* Setup command will now start an install if everything was successful copied.
* Cleanup code style (pep8 linting)

### CODE REVIEW

**Comment by nawuko** [comment]
Could you explain further?

**Comment by iiPlasma** [comment]
If you look at the structure at the config and how I iterate through them, it's a python dictionary so if you pass the key aka the entire package you can then just access the name and commands from within the values

**Comment by nawuko** [comment]
Please look at https://github.com/iiPlasma/sequestrum/pull/6/commits/e306e21a4b78ca2b9e132dcd48fc4ee640520fba
I'm quite happy with that structure.

**Comment by iiPlasma** [comment]
Can you load other modules in a module? I believe I tried that and it didn't work

**Comment by nawuko** [comment]
ofc you can :)

**Pull request merged**
